Aplikacje/apps/category/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static


urlpatterns = patterns('',
    url(r'^$', 'category.views.list_main_categories',name='list_main_categories'),
    url(r'^(?P<id>\d+)/$', 'category.views.list_sub_categories', name='list_sub_categories'),
    url(r'^category/(?P<id>\d+)/edit/$', 'category.views.edit_category', name='edit_category'),
    url(r'^category/(?P<id>\d+)/delete/$', 'category.views.delete_category', name='delete_category'),
    url(r'^task/(?P<id>\d+)/edit/$', 'category.views.edit_task', name='edit_task'),
    url(r'^task/(?P<id>\d+)/delete/$', 'category.views.delete_task', name='delete_task'),
)

Aplikacje/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('category.urls')),
    url(r'^user/', include('users.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplikacje/apps/category/models.py
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from django.db import models
# Create your models here.



class Category(MPTTModel):
    nazwa=models.CharField(max_length=50, null=False, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', verbose_name='Nad Kategoria')

    def __unicode__(self):
        if self.parent==None:
            return "%s" %(self.nazwa)
        else:
            return "%s -> %s" %(self.nazwa,self.parent)

    class MPTTMeta:
        order_insertion_by = ['nazwa']

Aplikacje/apps/tasks/models.py
from django.db import models

# Create your models here.
class Tasks(models.Model):
    id_kat = models.ForeignKey('category.Category', verbose_name='Nazwa nad kategorii', blank=True, null=True)
    nazwa = models.CharField(max_length=155, verbose_name='Nazwa')
    plik_pdf = models.FileField(verbose_name='Plik', upload_to='pliki_pdf/%Y/%m/%d')
    trudnosc = models.IntegerField(verbose_name='Trudnosc', max_length=1)

Aplikacje/apps/category/forms.py
# -*- coding: utf-8 -*-
__author__ = 'wojtek'
from django import forms

from django.forms import ModelForm, models, fields, Form

from category.models import Category

class CategoryForm(forms.ModelForm):

    def clean_nazwa(self):
        value = self.cleaned_data['nazwa']
        if value == u'Mati':
            raise forms.ValidationError('Matiego nie chcemy!!!')
        return value

    def __init__(self,*args, **kwargs):
        parent = kwargs.pop('parent',None)
        super(CategoryForm, self).__init__(*args, **kwargs)
        if parent!=None:
            self.fields['parent'].initial = parent

    class Meta:
        model = Category

Aplikacje/apps/category/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from category.forms import CategoryForm
from category.models import Category
from tasks.forms import TasksForm
from tasks.models import Tasks


def list_main_categories(request):
    context={
        'categories': Category.objects.filter(parent=None),
        'tasks': Tasks.objects.filter(id_kat=None),
    }
    if request.POST:
        print request.POST
        if len([x for x in request.POST.keys() if 'task' in x])>0:
            taskForm = TasksForm(request.POST, request.FILES, prefix='task')
            if taskForm.is_valid():
                taskForm.save(commit=True)
            form = CategoryForm(prefix='category')

        if len([x for x in request.POST.keys() if 'category' in x])>0:
            form = CategoryForm(request.POST, prefix='category')
            if form.is_valid():
                form.save(commit=True)
            taskForm = TasksForm(prefix='task')

    else:
        form = CategoryForm(prefix='category')
        taskForm = TasksForm(prefix='task')
    context.update({
        'form': form,
        'taskForm': taskForm
    })
    return TemplateResponse(request,"index.html",context)

def list_sub_categories(request, id):

    parent = get_object_or_404(Category, pk = id)
    kwargs = {'parent': parent}
    form = CategoryForm(prefix='category', **kwargs)
    kwargs = {'id_kat': parent}
    taskForm = TasksForm(prefix='task', **kwargs)

    context={
        'categories': Category.objects.filter(parent=id),
        'tasks': Tasks.objects.filter(id_kat=id),
        'form': form,
        'taskForm': taskForm
    }

    return TemplateResponse(request,"index.html",context)

@login_required
def edit_category(request, id):
    category = get_object_or_404(Category,pk=id)

    if request.POST:
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('list_main_categories'))
        else:
            context = {
                'category': category,
                'form': form
            }
    else:
        form = CategoryForm(instance=category)

        context = {
            'category': category,
            'form': form,
        }
    return TemplateResponse(request,"edit.html",context)

@login_required
def edit_task(request, id):
    task = get_object_or_404(Tasks,pk=id)

    if request.POST:
        form = TasksForm(request.POST, request.FILES, instance=task)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('list_main_categories'))
        else:
            context = {
                'task': task,
                'form': form
            }
    else:
        form = TasksForm(instance=task)

        context = {
            'task': task,
            'form': form,
        }
    return TemplateResponse(request,"edit_task.html",context)

@login_required
def delete_task(request, id):
    task = get_object_or_404(Tasks,pk=id)
    task.delete()
    return redirect(request.META['HTTP_REFERER'])


@login_required
def delete_category(request, id):
    category = get_object_or_404(Category,pk=id)
    category.delete()
    return redirect(request.META['HTTP_REFERER'])

Aplikacje/apps/category/templates/categories_tree.html
{% load mptt_tags %}
{% if nodes %}
<ul>
{% recursetree nodes %}
        {% if node.is_leaf_node %}
            <li>
            <span>
                <a href="{% url "list_sub_categories" node.pk %}">{{node.nazwa}}</a>
            </span>
            </li>
        {% else %}
            <li>
                <span><a href="{% url "list_sub_categories" node.pk %}">{{node.nazwa}}</a></span>
                <ul>
                    {{ children }}
                </ul>
            </li>
        {% endif %}
{% endrecursetree %}
</ul>
{% endif %}

Aplikacje/apps/category/templates/edit.html
{% extends 'base.html' %}
{% load i18n %}
{% load listMainCategories %}
{% block extra-css %}
{% endblock %}

{% block extra-js %}
{% endblock %}


{% block base_content %}

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="{% url "list_main_categories" %}">Kategorie</a>
        {% listMainCategories request %}
  </div>
</div>


    <div class="container">
    <h3>Edycja Kategorii</h3>
    <hr>
    <div class="row-fluid">
    <div class="span3">
        {% listMainCategoriesUl request %}
    </div>
    <div class="span6">
        <form action="#" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-default" onClick="$('form').submit();">
                                        {% trans "Save" %}
        </button>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

Aplikacje/apps/category/templates/edit_task.html
{% extends 'base.html' %}
{% load i18n %}
{% load listMainCategories %}
{% block extra-css %}
{% endblock %}

{% block extra-js %}
<script type="text/javascript">
$(document).ready(function(){

      $("#vote").jRating({
            step:true,
            length : 20, // nb of stars
            onClick : function(element,rate) {
                $('#id_trudnosc').val(rate);
            }
       });

});
</script>
{% endblock %}


{% block base_content %}

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="{% url "list_main_categories" %}">Kategorie</a>
        {% listMainCategories request %}
  </div>
</div>


    <div class="container">
    <h3>Formularz edycji zadania do kategorii</h3>
    <hr>
    <div class="col-lg-6">
        <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="vote" data-average="20" data-id="1"></div>
        <br>
        <button class="btn btn-default" onClick="$('#task').submit();">
                                        {% trans "Save" %}
        </button>
        </form>
    </div>

    </div>
{% endblock %}

Aplikacje/apps/category/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load listMainCategories %}
{% block extra-css %}
{% endblock %}

{% block extra-js %}
    <script type="text/javascript">
$(document).ready(function(){

      $("#vote").jRating({
            step:true,
            length : 20, // nb of stars
            onClick : function(element,rate) {
                $('#id_task-trudnosc').val(rate);
            }
       });

});
</script>
{% endblock %}


{% block base_content %}

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="{% url "list_main_categories" %}">Kategorie</a>
        {% listMainCategories request %}
  </div>
</div>


    <div class="container">
    {% if request.user.is_authenticated  %}
    <hr>
    <div class="row">
    <div class="span6">
        <h4>Formularz dodania kategorii</h4>
        <form action="{% url "list_main_categories" %}" method="post" id="category">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button class="btn btn-default" onClick="$('#category').submit();">
                                        {% trans "Save" %}
        </button>
        </form>
    </div>

    <div class="span6">
        <h4>Formularz dodania zadania do kategorii</h4>
        <form action="{% url "list_main_categories" %}" method="post" id="task" enctype="multipart/form-data">
        {% csrf_token %}
        {{ taskForm.as_p }}
        <div id="vote" data-average="20" data-id="1"></div>
        <br>
        <button class="btn btn-default" onClick="$('#task').submit();">
                                        {% trans "Save" %}
        </button>
        </form>
    </div>
    </div>
    {% endif %}

    <hr>

    <div class="accordion well well-small" id="accordion2">

            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse"
                   data-parent="#accordion2" href="#collapseOne">Kategorie</a>
                <div id="collapseOne" class="accordion-body collapse">
                <div class="accordion-inner">
                    <div class="tree well">
                        {% categories request %}
                    </div>
                </div>
                </div>
            </div>
    </div>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Nazwa</th>
            <th>Nad Kategoria</th>
            <th>Edycja</th>
        </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td><a href="{% url "list_sub_categories" category.pk %}">{{ category.nazwa }}</a></td>
                <td>{{ category.parent|default_if_none:"Brak" }}</td>
                <td>
                    <a href="{% url "edit_category" category.pk %}"><span class="icon-edit"> </span> edycja</a>
                    <br>
                    <a href="{% url "delete_category" category.pk %}"><span class="icon-remove"> </span> usuń</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <br><br>

    <div class="well well-small">
        Zadania
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Nad Kategoria</th>
                <th>Trudnosc</th>
                <th>Plik</th>
                <th>Edycja</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td><a href="{{ task.plik_pdf.url }}">{{ task.nazwa }}</a></td>
                <td>{{ task.id_kat|default_if_none:"Brak" }}</td>
                <td>{{ task.trudnosc|default_if_none:"Brak" }}/20</td>
                <td><a href="{{ task.plik_pdf.url }}"><span class="icon-edit"> </span> Plik</a></td>
                <td>
                    <a href="{% url "edit_task" task.pk %}"><span class="icon-edit"> </span> edycja</a><br>
                    <a href="{% url "delete_task" task.pk %}"><span class="icon-remove"> </span> usuń</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    </div>
{% endblock %}

Aplikacje/apps/category/templates/main_categories.html
{% load mptt_tags %}
<ul id="nav">
{% if nodes %}
{% recursetree nodes %}
        {% if node.is_leaf_node %}
            <li>
                <a href="{% url "list_sub_categories" node.pk %}">{{node.nazwa}}</a>
            </li>
        {% else %}
            <li>
                <a href="{% url "list_sub_categories" node.pk %}">{{node.nazwa}}</a>
                <ul>
                    {{ children }}
                </ul>
            </li>
        {% endif %}
{% endrecursetree %}

{% else %}
    {% if request.user.is_authenticated  %}
        <li><a href="#category">Brak kategorii, dodaj nową</a></li>
    {% else %}
        <li><a href="{% url "login_user" %}">Brak kategorii, zaloguj się by móc dodać nową</a></li>
    {% endif %}
{% endif%}
    {% if request.user.is_authenticated  %}
        <li class="pull-right"><a href="{% url "logout_user" %}">Wyloguj - {{ request.user }}</a></li>
    {% else %}
        <li class="pull-right"><a href="{% url "login_user" %}">Zaloguj</a></li>
    {% endif %}
</ul>

Aplikacje/apps/category/templates/main_categories_ul.html
<ul class="nav nav-list bs-docs-sidenav affix-top">
{% if main_categories %}
    {% for link in main_categories %}
    <li><a href="{% url "list_sub_categories" link.pk %}"><i class="icon-chevron-right"></i> {{link}}</a></li>
    {% endfor %}
{% else %}
    {% if request.user.is_authenticated  %}
        <li><a href="#category">Brak kategorii, dodaj nową</a></li>
    {% else %}
        <li><a href="{% url "login_user" %}">Brak kategorii, zaloguj się by móc dodać nową</a></li>
    {% endif %}
{% endif%}
    {% if request.user.is_authenticated  %}
        <li class=""><a href="{% url "logout_user" %}">Wyloguj - {{ request.user }}</a></li>
    {% else %}
        <li class=""><a href="{% url "login_user" %}">Zaloguj</a></li>
    {% endif %}
</ul>